-- 0039: Mega Store Customer Reward Cycle - DATABASE FOUNDATION (hardening + missing pieces). Re-runnable.
-- Run AFTER 0038. Frontend does NOT need to change for this migration.
--
-- 0038 already created: mega_stores, mega_campaigns, mega_campaign_shops, mega_enrollments, mega_rewards and the
-- megastore_* / admin_megastore_* / join_mega_campaign / get_my_mega_rewards functions. Those tables are REUSED here.
-- Nothing is dropped. No existing RLS policy is weakened (one is extended to authorised members, see section 9).
--
-- NEW in this file
--   1. mega_store_members              authorised owners / managers of a Mega Store (primary owner is always a member)
--   2. mega_campaigns.budget_inr, .config   campaign budget + free configuration (json object)
--   3. mega_terms, mega_terms_acceptances   versioned campaign terms + who accepted what (customers and partner shops)
--   4. mega_partner_participation      partner shop invited / accepted / declined / withdrawn / removed
--   5. mega_service_verifications      the verified partner-shop service every reward must be linked to
--   6. mega_reward_redemptions         redemption records, kept SEPARATE from enrolments (participation)
--   7. mega_fraud_flags                fraud-review flags + decisions
--   8. mega_audit_log                  append-only audit trail (campaign, budget, reward, redemption, terms, flags ...)
--   9. Database-level guards (triggers) so the business rules hold even if a function is bypassed:
--        - one enrolment per customer per campaign (unique, from 0038) + customer must be a real active customer account
--        - max 5 rewards per customer per campaign (reward_seq 1..5 + partial unique index + count check, under a row lock)
--        - every reward is linked to customer + campaign + Mega Store + verified partner-shop service
--        - reward code is generated by the server (64-bit random, unpredictable); browser values for code / amount are ignored
--        - expires_at = issued_at + 1 month (UTC), forced by the server
--        - a reward can be redeemed once; redeemed / revoked / rejected are final; discount is re-checked against the formula
--        - campaign budget is enforced when a redemption is recorded
--        - campaign reward terms are locked after the draft stage
--
-- FINANCIAL RULE (unchanged): the Mega Store funds 100% of the discount; nothing here touches Blisscco credit / payment tables.
-- SECURITY: all new tables are read-only for API users (RLS select policies only). Every write goes through the security-definer
-- functions / triggers in this file. Nothing here needs, stores or exposes a service-role key.

-- ============ 1. AUTHORISED OWNERS ============
create table if not exists public.mega_store_members (
  mega_store_id uuid not null references public.mega_stores(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  member_role text not null default 'manager' check (member_role in ('owner', 'manager')),
  status text not null default 'active' check (status in ('active', 'revoked')),
  added_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  primary key (mega_store_id, user_id)
);
create index if not exists mega_store_members_user_idx on public.mega_store_members (user_id) where status = 'active';

-- ============ 2. COLUMNS ON EXISTING TABLES (additive only) ============
alter table public.mega_campaigns add column if not exists budget_inr numeric(12, 2)
  check (budget_inr is null or budget_inr > 0);                                      -- optional cap on the TOTAL discount given
alter table public.mega_campaigns add column if not exists config jsonb not null default '{}'::jsonb
  check (jsonb_typeof(config) = 'object' and octet_length(config::text) <= 4000);    -- free campaign settings (object, max 4 KB)
alter table public.mega_enrollments add column if not exists terms_id uuid;           -- the customer terms version accepted at joining
alter table public.mega_rewards add column if not exists reward_seq smallint;         -- 1..5: which of the customer's rewards this is
alter table public.mega_rewards add column if not exists service_verification_id uuid;

alter table public.mega_rewards drop constraint if exists mega_reward_seq_ok;
alter table public.mega_rewards add constraint mega_reward_seq_ok check (reward_seq is null or reward_seq between 1 and 5);
-- hard database cap: a customer can never hold two counted rewards with the same sequence number, and the number is 1..5
create unique index if not exists mega_rewards_seq_unique on public.mega_rewards (campaign_id, customer_id, reward_seq)
  where reward_seq is not null and status in ('active', 'on_hold', 'redeemed');
create index if not exists mega_rewards_expiry_idx on public.mega_rewards (expires_at) where status = 'active';

-- ============ 3. NEW TABLES ============
-- 5. verified partner-shop service (one row per booking that earned / could earn a reward)
create table if not exists public.mega_service_verifications (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null unique references public.bookings(id) on delete restrict,
  campaign_id uuid not null references public.mega_campaigns(id) on delete cascade,
  mega_store_id uuid not null references public.mega_stores(id) on delete cascade,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  business_id uuid not null references public.businesses(id) on delete restrict,
  service_label text,
  service_price_inr numeric(10, 2) not null check (service_price_inr > 0),
  service_completed_at timestamptz,
  status text not null default 'verified' check (status in ('verified', 'revoked', 'rejected')),
  method text not null default 'booking_completed' check (method in ('booking_completed', 'admin')),
  verified_at timestamptz not null default now(),
  verified_by uuid references public.profiles(id) on delete set null,
  note text check (note is null or char_length(note) <= 300),
  created_at timestamptz not null default now()
);
create index if not exists mega_sv_business_idx on public.mega_service_verifications (business_id, verified_at desc);
create index if not exists mega_sv_campaign_customer_idx on public.mega_service_verifications (campaign_id, customer_id);
create index if not exists mega_sv_store_idx on public.mega_service_verifications (mega_store_id, status);

-- 3. versioned terms. campaign_id null = platform default for all campaigns. Rows are never edited: a change = a new version.
create table if not exists public.mega_terms (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid references public.mega_campaigns(id) on delete cascade,
  scope text not null check (scope in ('customer', 'partner')),
  version int not null check (version > 0),
  title text not null check (char_length(trim(title)) between 3 and 120),
  body_md text not null check (char_length(body_md) between 20 and 20000),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create unique index if not exists mega_terms_version_unique on public.mega_terms
  (coalesce(campaign_id, '00000000-0000-0000-0000-000000000000'::uuid), scope, version);

create table if not exists public.mega_terms_acceptances (
  id uuid primary key default gen_random_uuid(),
  terms_id uuid not null references public.mega_terms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  campaign_id uuid not null references public.mega_campaigns(id) on delete cascade,
  scope text not null check (scope in ('customer', 'partner')),
  business_id uuid references public.businesses(id) on delete cascade,               -- set for partner-shop acceptance
  accepted_at timestamptz not null default now(),
  constraint mega_terms_acc_shape check ((scope = 'partner' and business_id is not null) or (scope = 'customer' and business_id is null))
);
create unique index if not exists mega_terms_acc_unique on public.mega_terms_acceptances
  (terms_id, user_id, campaign_id, coalesce(business_id, '00000000-0000-0000-0000-000000000000'::uuid));
create index if not exists mega_terms_acc_user_idx on public.mega_terms_acceptances (user_id);
create index if not exists mega_terms_acc_campaign_idx on public.mega_terms_acceptances (campaign_id, scope);

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'mega_enrollments_terms_fk') then
    alter table public.mega_enrollments add constraint mega_enrollments_terms_fk
      foreign key (terms_id) references public.mega_terms(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'mega_rewards_verification_fk') then
    alter table public.mega_rewards add constraint mega_rewards_verification_fk
      foreign key (service_verification_id) references public.mega_service_verifications(id) on delete set null;
  end if;
end $$;

-- 4. partner participation (the selection itself stays in mega_campaign_shops)
create table if not exists public.mega_partner_participation (
  campaign_id uuid not null references public.mega_campaigns(id) on delete cascade,
  business_id uuid not null references public.businesses(id) on delete cascade,
  status text not null default 'invited' check (status in ('invited', 'accepted', 'declined', 'withdrawn', 'removed')),
  invited_at timestamptz not null default now(),
  responded_at timestamptz,
  responded_by uuid references public.profiles(id) on delete set null,
  terms_id uuid references public.mega_terms(id) on delete set null,
  primary key (campaign_id, business_id)
);
create index if not exists mega_pp_business_idx on public.mega_partner_participation (business_id, status);

-- 6. redemptions (separate from enrolments = participation)
create table if not exists public.mega_reward_redemptions (
  id uuid primary key default gen_random_uuid(),
  reward_id uuid not null unique references public.mega_rewards(id) on delete cascade,      -- UNIQUE: a reward is redeemed once
  campaign_id uuid not null references public.mega_campaigns(id) on delete cascade,
  mega_store_id uuid not null references public.mega_stores(id) on delete cascade,
  customer_id uuid not null references public.profiles(id) on delete cascade,
  redeemed_by uuid references public.profiles(id) on delete set null,
  bill_inr numeric(10, 2) not null check (bill_inr > 0),
  discount_inr numeric(10, 2) not null check (discount_inr >= 0),
  redeemed_at timestamptz not null default now(),
  constraint mega_redemption_discount_ok check (discount_inr <= bill_inr)
);
create index if not exists mega_redemptions_campaign_idx on public.mega_reward_redemptions (campaign_id, redeemed_at desc);
create index if not exists mega_redemptions_customer_idx on public.mega_reward_redemptions (customer_id, redeemed_at desc);
create index if not exists mega_redemptions_store_idx on public.mega_reward_redemptions (mega_store_id, redeemed_at desc);

-- 9. fraud-review flags
create table if not exists public.mega_fraud_flags (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.mega_campaigns(id) on delete cascade,
  mega_store_id uuid not null references public.mega_stores(id) on delete cascade,
  reward_id uuid references public.mega_rewards(id) on delete cascade,
  customer_id uuid references public.profiles(id) on delete cascade,
  business_id uuid references public.businesses(id) on delete cascade,
  flag_type text not null check (flag_type ~ '^[a-z0-9_]{3,40}$'),
  severity text not null default 'medium' check (severity in ('low', 'medium', 'high')),
  source text not null default 'system' check (source in ('system', 'admin')),
  status text not null default 'open' check (status in ('open', 'cleared', 'confirmed')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  review_note text check (review_note is null or char_length(review_note) <= 300)
);
create unique index if not exists mega_fraud_flags_reward_type on public.mega_fraud_flags (reward_id, flag_type) where reward_id is not null;
create index if not exists mega_fraud_flags_status_idx on public.mega_fraud_flags (status, created_at desc);
create index if not exists mega_fraud_flags_campaign_idx on public.mega_fraud_flags (campaign_id, status);
create index if not exists mega_fraud_flags_customer_idx on public.mega_fraud_flags (customer_id) where customer_id is not null;

-- 8. audit log (append-only; no foreign keys so the trail survives deletions)
create table if not exists public.mega_audit_log (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  actor_id uuid,
  actor_role text,
  mega_store_id uuid,
  campaign_id uuid,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  details jsonb not null default '{}'::jsonb
);
create index if not exists mega_audit_campaign_idx on public.mega_audit_log (campaign_id, created_at desc);
create index if not exists mega_audit_store_idx on public.mega_audit_log (mega_store_id, created_at desc);
create index if not exists mega_audit_entity_idx on public.mega_audit_log (entity_type, entity_id);

-- ============ 4. HELPERS ============
-- Authorised owner = the primary owner (as before) OR an active member added by the primary owner. Suspended accounts never qualify.
create or replace function public.owns_mega_store(p_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.mega_stores m
                  where m.id = p_id
                    and exists (select 1 from public.profiles p where p.id = auth.uid() and not p.is_suspended)
                    and (m.owner_id = auth.uid()
                         or exists (select 1 from public.mega_store_members mm
                                     where mm.mega_store_id = m.id and mm.user_id = auth.uid() and mm.status = 'active')));
$$;

create or replace function public.owns_mega_campaign(p_campaign_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.mega_campaigns c where c.id = p_campaign_id and public.owns_mega_store(c.mega_store_id));
$$;

-- terms are readable when they are platform defaults, or the campaign is not a draft, or the reader runs it / is admin / is a selected partner
create or replace function public.mega_terms_visible(p_campaign_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select p_campaign_id is null or exists (
    select 1 from public.mega_campaigns c
     where c.id = p_campaign_id
       and (c.status <> 'draft' or public.owns_mega_store(c.mega_store_id) or public.is_admin()
            or exists (select 1 from public.mega_campaign_shops s where s.campaign_id = c.id and public.owns_business(s.business_id))));
$$;

-- current terms = newest version for the campaign, else newest platform default (internal)
create or replace function public.mega_current_terms(p_campaign_id uuid, p_scope text)
returns uuid language sql stable security definer set search_path = '' as $$
  select x.id from (
    select t.id, 1 as pri, t.version from public.mega_terms t where t.scope = p_scope and t.campaign_id = p_campaign_id
    union all
    select t.id, 2 as pri, t.version from public.mega_terms t where t.scope = p_scope and t.campaign_id is null
  ) x order by x.pri, x.version desc limit 1;
$$;

-- unpredictable reward identifier: 64 random bits from gen_random_uuid() (cryptographically strong), shown as text and QR
create or replace function public.mega_new_reward_code() returns text
language plpgsql volatile security definer set search_path = '' as $$
declare h text := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8) || substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
begin
  return 'MS-' || substr(h, 1, 4) || '-' || substr(h, 5, 4) || '-' || substr(h, 9, 4) || '-' || substr(h, 13, 4);
end $$;

-- internal audit writer (not callable by API users)
create or replace function public.mega_audit(p_action text, p_store uuid, p_campaign uuid, p_type text, p_id uuid, p_details jsonb)
returns void language plpgsql security definer set search_path = '' as $$
begin
  insert into public.mega_audit_log (actor_id, actor_role, mega_store_id, campaign_id, action, entity_type, entity_id, details)
  values (auth.uid(), (select p.role::text from public.profiles p where p.id = auth.uid()), p_store, p_campaign, p_action, p_type, p_id,
          coalesce(p_details, '{}'::jsonb));
end $$;

-- ============ 5. BACKFILL OF EXISTING 0038 DATA (guards are created AFTER this, so nothing is blocked or double-logged) ============
drop trigger if exists mega_rewards_guard on public.mega_rewards;
drop trigger if exists mega_rewards_after on public.mega_rewards;
drop trigger if exists mega_redemptions_guard on public.mega_reward_redemptions;

insert into public.mega_store_members (mega_store_id, user_id, member_role, added_by)
select id, owner_id, 'owner', owner_id from public.mega_stores
on conflict do nothing;

insert into public.mega_partner_participation (campaign_id, business_id, invited_at)
select campaign_id, business_id, added_at from public.mega_campaign_shops
on conflict do nothing;

insert into public.mega_service_verifications (booking_id, campaign_id, mega_store_id, customer_id, business_id, service_label,
                                               service_price_inr, service_completed_at, verified_at)
select r.booking_id, r.campaign_id, r.mega_store_id, r.customer_id, r.business_id, b.service_label, b.price_inr, b.completed_at, r.created_at
  from public.mega_rewards r join public.bookings b on b.id = r.booking_id
on conflict (booking_id) do nothing;

update public.mega_rewards r set service_verification_id = v.id
  from public.mega_service_verifications v
 where v.booking_id = r.booking_id and r.service_verification_id is null;

with ranked as (
  select id, row_number() over (partition by campaign_id, customer_id order by created_at, id) as rn
    from public.mega_rewards where status in ('active', 'on_hold', 'redeemed') and reward_seq is null)
update public.mega_rewards r set reward_seq = ranked.rn::smallint
  from ranked where ranked.id = r.id and ranked.rn <= 5;

insert into public.mega_reward_redemptions (reward_id, campaign_id, mega_store_id, customer_id, bill_inr, discount_inr, redeemed_at)
select id, campaign_id, mega_store_id, customer_id, redeemed_bill_inr, discount_given_inr, coalesce(redeemed_at, created_at)
  from public.mega_rewards
 where status = 'redeemed' and redeemed_bill_inr is not null and discount_given_inr is not null
on conflict (reward_id) do nothing;

insert into public.mega_fraud_flags (campaign_id, mega_store_id, reward_id, customer_id, business_id, flag_type, status, details)
select r.campaign_id, r.mega_store_id, r.id, r.customer_id, r.business_id,
       lower(regexp_replace(f.v, '[^a-zA-Z0-9_]', '_', 'g')),
       case r.status when 'on_hold' then 'open' when 'rejected' then 'confirmed' when 'revoked' then 'confirmed' else 'cleared' end,
       jsonb_build_object('backfilled', true)
  from public.mega_rewards r
  cross join lateral jsonb_array_elements_text(r.risk_flags) as f(v)
 where jsonb_typeof(r.risk_flags) = 'array' and char_length(f.v) between 3 and 40
on conflict do nothing;

-- ============ 6. GUARD + AUDIT TRIGGER FUNCTIONS ============
create or replace function public.mega_block_update() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  raise exception 'record_immutable' using errcode = '42501';
end $$;

-- members: the primary owner can never be demoted / revoked, and a member row never moves to another store or user
create or replace function public.mega_members_guard() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if new.mega_store_id <> old.mega_store_id or new.user_id <> old.user_id then raise exception 'record_immutable' using errcode = '42501'; end if;
  if exists (select 1 from public.mega_stores s where s.id = new.mega_store_id and s.owner_id = new.user_id)
     and (new.status <> 'active' or new.member_role <> 'owner') then
    raise exception 'primary_owner_locked';
  end if;
  return new;
end $$;

create or replace function public.mega_store_add_owner_member() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.mega_store_members (mega_store_id, user_id, member_role, added_by)
  values (new.id, new.owner_id, 'owner', new.owner_id) on conflict do nothing;
  return new;
end $$;

-- campaigns: reward terms are frozen once the campaign leaves draft; 'ended' is final; budget can never drop below what was spent
create or replace function public.mega_campaign_guard() returns trigger
language plpgsql security definer set search_path = '' as $$
declare v_spent numeric;
begin
  if new.mega_store_id <> old.mega_store_id then raise exception 'campaign_locked'; end if;
  if old.status = 'ended' and new.status <> 'ended' then raise exception 'invalid_transition'; end if;
  if old.status <> 'draft' and (new.reward_type <> old.reward_type or new.reward_value <> old.reward_value
       or new.max_discount_inr is distinct from old.max_discount_inr or new.min_purchase_inr <> old.min_purchase_inr
       or new.min_service_price_inr <> old.min_service_price_inr or new.max_rewards_per_customer <> old.max_rewards_per_customer
       or new.one_reward_per_shop <> old.one_reward_per_shop or new.starts_at <> old.starts_at) then
    raise exception 'campaign_locked';
  end if;
  if new.budget_inr is not null and new.budget_inr is distinct from old.budget_inr then
    select coalesce(sum(discount_inr), 0) into v_spent from public.mega_reward_redemptions where campaign_id = new.id;
    if new.budget_inr < v_spent then raise exception 'budget_below_spent'; end if;
  end if;
  return new;
end $$;

-- partner selection -> participation record. A shop that declined cannot be forced back in.
create or replace function public.mega_shop_link_guard() returns trigger
language plpgsql security definer set search_path = '' as $$
declare p public.mega_partner_participation;
begin
  select * into p from public.mega_partner_participation where campaign_id = new.campaign_id and business_id = new.business_id for update;
  if not found then
    insert into public.mega_partner_participation (campaign_id, business_id) values (new.campaign_id, new.business_id);
  elsif p.status = 'declined' then
    raise exception 'partner_declined';
  elsif p.status in ('withdrawn', 'removed') then
    update public.mega_partner_participation set status = 'invited', invited_at = now(), responded_at = null, responded_by = null, terms_id = null
     where campaign_id = new.campaign_id and business_id = new.business_id;
  end if;
  return new;
end $$;

create or replace function public.mega_shop_unlink() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  update public.mega_partner_participation set status = 'removed', responded_at = now()
   where campaign_id = old.campaign_id and business_id = old.business_id and status in ('invited', 'accepted');
  return null;
end $$;

-- enrolment: authenticated real customer, active campaign, accepted terms (when terms exist). Duplicates are left to the unique key.
create or replace function public.mega_enrollment_guard() returns trigger
language plpgsql security definer set search_path = '' as $$
declare c public.mega_campaigns; ms public.mega_stores; pr public.profiles; v_terms uuid;
begin
  if exists (select 1 from public.mega_enrollments where campaign_id = new.campaign_id and customer_id = new.customer_id) then
    return new;                                         -- already joined: ON CONFLICT DO NOTHING (or the unique key) handles it
  end if;
  select * into c from public.mega_campaigns where id = new.campaign_id;
  if not found or c.status <> 'active' or c.ends_at <= now() then raise exception 'not_active'; end if;
  select * into ms from public.mega_stores where id = c.mega_store_id;
  if ms.status <> 'approved' then raise exception 'store_not_approved'; end if;
  select * into pr from public.profiles where id = new.customer_id;
  if not found or pr.is_suspended or pr.role <> 'customer' then raise exception 'customer_only'; end if;
  if ms.owner_id = new.customer_id then raise exception 'own_store'; end if;
  v_terms := public.mega_current_terms(c.id, 'customer');
  if v_terms is not null then
    if not exists (select 1 from public.mega_terms_acceptances a
                    where a.terms_id = v_terms and a.user_id = new.customer_id and a.campaign_id = c.id and a.business_id is null) then
      raise exception 'terms_not_accepted';
    end if;
    new.terms_id := v_terms;
  end if;
  return new;
end $$;

-- rewards: THE central guard. Runs for every role (including the table owner), so the rules cannot be skipped by a bad function.
create or replace function public.mega_reward_guard() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  c public.mega_campaigns; ms public.mega_stores; bk public.bookings; biz public.businesses; en public.mega_enrollments;
  v_ver public.mega_service_verifications; v_seq smallint; v_spent numeric; v_exp numeric;
begin
  if tg_op = 'INSERT' then
    if new.status not in ('active', 'on_hold') or new.redeemed_at is not null or new.redeemed_bill_inr is not null
       or new.discount_given_inr is not null then
      raise exception 'invalid_initial_status';
    end if;
    select * into c from public.mega_campaigns where id = new.campaign_id;
    if not found or c.mega_store_id <> new.mega_store_id then raise exception 'campaign_mismatch'; end if;
    select * into ms from public.mega_stores where id = c.mega_store_id;
    -- the customer must have joined; this row lock serialises two rewards for the same customer (so the cap cannot be beaten)
    select * into en from public.mega_enrollments where campaign_id = c.id and customer_id = new.customer_id for update;
    if not found then raise exception 'not_enrolled'; end if;
    -- the verified partner-shop service
    select * into bk from public.bookings where id = new.booking_id;
    if not found or bk.status <> 'completed' or bk.source <> 'customer' or bk.customer_id is distinct from new.customer_id
       or bk.business_id <> new.business_id then
      raise exception 'service_not_verified';
    end if;
    select * into biz from public.businesses where id = bk.business_id;
    if not exists (select 1 from public.mega_campaign_shops s where s.campaign_id = c.id and s.business_id = bk.business_id) then
      raise exception 'not_partner_shop';
    end if;
    if ms.owner_id = new.customer_id or ms.owner_id = biz.owner_id or biz.owner_id = new.customer_id then raise exception 'self_dealing'; end if;
    -- cap: at most max_rewards_per_customer (never more than 5)
    if (select count(*) from public.mega_rewards x where x.campaign_id = c.id and x.customer_id = new.customer_id
          and x.status in ('active', 'on_hold', 'redeemed')) >= least(c.max_rewards_per_customer, 5) then
      raise exception 'reward_limit_reached';
    end if;
    select min(g) into v_seq from generate_series(1, least(c.max_rewards_per_customer, 5)) g
     where not exists (select 1 from public.mega_rewards x where x.campaign_id = c.id and x.customer_id = new.customer_id
                         and x.reward_seq = g and x.status in ('active', 'on_hold', 'redeemed'));
    if v_seq is null then raise exception 'reward_limit_reached'; end if;
    if c.one_reward_per_shop and exists (select 1 from public.mega_rewards x where x.campaign_id = c.id and x.customer_id = new.customer_id
          and x.business_id = new.business_id and x.status in ('active', 'on_hold', 'redeemed')) then
      raise exception 'duplicate_shop';
    end if;
    if c.budget_inr is not null then
      select coalesce(sum(discount_inr), 0) into v_spent from public.mega_reward_redemptions where campaign_id = c.id;
      if v_spent >= c.budget_inr then raise exception 'budget_exhausted'; end if;
    end if;
    -- link / create the verification record
    insert into public.mega_service_verifications (booking_id, campaign_id, mega_store_id, customer_id, business_id, service_label,
                                                   service_price_inr, service_completed_at)
    values (bk.id, c.id, ms.id, bk.customer_id, bk.business_id, bk.service_label, bk.price_inr, bk.completed_at)
    on conflict (booking_id) do nothing;
    select * into v_ver from public.mega_service_verifications where booking_id = bk.id;
    if v_ver.status <> 'verified' or v_ver.campaign_id <> c.id or v_ver.customer_id <> new.customer_id then
      raise exception 'service_not_verified';
    end if;
    -- never trust the caller: terms, identifier, sequence and clock come from the server
    new.service_verification_id := v_ver.id;
    new.reward_seq := v_seq;
    new.reward_type := c.reward_type;
    new.reward_value := c.reward_value;
    new.max_discount_inr := c.max_discount_inr;
    new.min_purchase_inr := c.min_purchase_inr;
    new.business_name := biz.name;
    new.code := public.mega_new_reward_code();
    if new.risk_flags is null or jsonb_typeof(new.risk_flags) <> 'array' then new.risk_flags := '[]'::jsonb; end if;
    if new.status = 'active' then
      new.issued_at := now();
      new.expires_at := ((now() at time zone 'UTC') + interval '1 month') at time zone 'UTC';
    else
      new.issued_at := null; new.expires_at := null;
    end if;
    return new;
  end if;

  -- UPDATE
  if new.id <> old.id or new.campaign_id <> old.campaign_id or new.mega_store_id <> old.mega_store_id
     or new.customer_id <> old.customer_id or new.booking_id <> old.booking_id or new.business_id <> old.business_id
     or new.code <> old.code or new.business_name <> old.business_name or new.reward_type <> old.reward_type
     or new.reward_value <> old.reward_value or new.max_discount_inr is distinct from old.max_discount_inr
     or new.min_purchase_inr <> old.min_purchase_inr or new.reward_seq is distinct from old.reward_seq
     or (new.service_verification_id is distinct from old.service_verification_id and new.service_verification_id is not null)
     or new.created_at <> old.created_at or new.funded_by <> old.funded_by then
    raise exception 'reward_immutable';
  end if;

  if new.status is distinct from old.status then
    if not ((old.status = 'on_hold' and new.status in ('active', 'rejected', 'revoked'))
         or (old.status = 'active' and new.status in ('redeemed', 'revoked'))) then
      raise exception 'invalid_transition';
    end if;
    if new.status = 'active' then                                   -- released from hold: the one-month clock starts now
      new.issued_at := now();
      new.expires_at := ((now() at time zone 'UTC') + interval '1 month') at time zone 'UTC';
    elsif new.status = 'redeemed' then
      if old.expires_at is null or old.expires_at <= now() then raise exception 'expired'; end if;
      if new.redeemed_bill_inr is null or new.redeemed_bill_inr <= 0 or new.discount_given_inr is null or new.discount_given_inr < 0 then
        raise exception 'invalid_bill';
      end if;
      if new.redeemed_bill_inr < old.min_purchase_inr then raise exception 'below_min_purchase'; end if;
      v_exp := case when old.reward_type = 'percent' then round(new.redeemed_bill_inr * old.reward_value / 100, 2) else old.reward_value end;
      if old.reward_type = 'percent' and old.max_discount_inr is not null then v_exp := least(v_exp, old.max_discount_inr); end if;
      v_exp := least(v_exp, new.redeemed_bill_inr);
      if abs(new.discount_given_inr - v_exp) > 0.01 then raise exception 'discount_mismatch'; end if;     -- 1 paisa tolerance for rounding of the bill
      new.redeemed_at := now();
    end if;
  else
    -- final rows never change (only 'reviewed_by' may become null when that reviewer's account is deleted)
    if old.status in ('redeemed', 'revoked', 'rejected') and (to_jsonb(new) - 'reviewed_by') is distinct from (to_jsonb(old) - 'reviewed_by') then
      raise exception 'reward_final';
    end if;
    if new.issued_at is distinct from old.issued_at or new.expires_at is distinct from old.expires_at then
      raise exception 'reward_immutable';
    end if;
  end if;
  return new;
end $$;

-- rewards: flags, redemption record, flag decisions, audit
create or replace function public.mega_reward_after() returns trigger
language plpgsql security definer set search_path = '' as $$
declare f text; v_type text;
begin
  if tg_op = 'INSERT' then
    for f in select jsonb_array_elements_text(new.risk_flags) loop
      v_type := lower(regexp_replace(f, '[^a-zA-Z0-9_]', '_', 'g'));
      if char_length(v_type) between 3 and 40 then
        insert into public.mega_fraud_flags (campaign_id, mega_store_id, reward_id, customer_id, business_id, flag_type, source, details)
        values (new.campaign_id, new.mega_store_id, new.id, new.customer_id, new.business_id, v_type, 'system',
                jsonb_build_object('booking_id', new.booking_id))
        on conflict do nothing;
      end if;
    end loop;
    perform public.mega_audit('reward.issue', new.mega_store_id, new.campaign_id, 'mega_reward', new.id,
      jsonb_build_object('status', new.status, 'booking_id', new.booking_id, 'seq', new.reward_seq, 'flags', new.risk_flags));
    return null;
  end if;

  if new.status is distinct from old.status then
    if new.status = 'redeemed' then
      insert into public.mega_reward_redemptions (reward_id, campaign_id, mega_store_id, customer_id, redeemed_by, bill_inr, discount_inr, redeemed_at)
      values (new.id, new.campaign_id, new.mega_store_id, new.customer_id, auth.uid(), new.redeemed_bill_inr, new.discount_given_inr, new.redeemed_at);
    end if;
    if old.status = 'on_hold' and new.status = 'active' then
      update public.mega_fraud_flags set status = 'cleared', reviewed_by = auth.uid(), reviewed_at = now()
       where reward_id = new.id and status = 'open';
    elsif new.status in ('rejected', 'revoked') then
      update public.mega_fraud_flags set status = 'confirmed', reviewed_by = auth.uid(), reviewed_at = now()
       where reward_id = new.id and status = 'open';
    end if;
    perform public.mega_audit('reward.' || new.status, new.mega_store_id, new.campaign_id, 'mega_reward', new.id,
      jsonb_build_object('from', old.status, 'to', new.status));
  end if;
  return null;
end $$;

-- redemption: the campaign budget is enforced here (row lock on the campaign, so two redemptions cannot both squeeze under it)
create or replace function public.mega_redemption_guard() returns trigger
language plpgsql security definer set search_path = '' as $$
declare c public.mega_campaigns; v_spent numeric;
begin
  select * into c from public.mega_campaigns where id = new.campaign_id for update;
  if not found then raise exception 'campaign_mismatch'; end if;
  if c.budget_inr is not null then
    select coalesce(sum(discount_inr), 0) into v_spent from public.mega_reward_redemptions where campaign_id = c.id;
    if v_spent + new.discount_inr > c.budget_inr then raise exception 'budget_exhausted'; end if;
  end if;
  return new;
end $$;

-- generic audit trigger for the other tables
create or replace function public.mega_audit_trigger() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  v_new jsonb := case when tg_op <> 'DELETE' then to_jsonb(new) end;
  v_old jsonb := case when tg_op <> 'INSERT' then to_jsonb(old) end;
  v_row jsonb;
  v_store uuid; v_camp uuid; v_ent uuid; v_action text; v_det jsonb := '{}'::jsonb;
begin
  v_row := coalesce(v_new, v_old);
  case tg_table_name
    when 'mega_stores' then
      v_store := (v_row->>'id')::uuid; v_ent := v_store;
      if tg_op = 'INSERT' then v_action := 'store.create';
      elsif v_new->>'status' is distinct from v_old->>'status' then
        v_action := 'store.' || (v_new->>'status'); v_det := jsonb_build_object('from', v_old->>'status', 'to', v_new->>'status');
      else return null; end if;
    when 'mega_campaigns' then
      v_store := (v_row->>'mega_store_id')::uuid; v_camp := (v_row->>'id')::uuid; v_ent := v_camp;
      if tg_op = 'INSERT' then
        v_action := 'campaign.create'; v_det := jsonb_build_object('status', v_new->>'status', 'budget_inr', v_new->>'budget_inr');
      else
        if v_new->>'status' is distinct from v_old->>'status' then
          v_action := 'campaign.' || (v_new->>'status'); v_det := jsonb_build_object('from', v_old->>'status', 'to', v_new->>'status');
        elsif v_new->>'budget_inr' is distinct from v_old->>'budget_inr' then
          v_action := 'campaign.budget'; v_det := jsonb_build_object('from', v_old->>'budget_inr', 'to', v_new->>'budget_inr');
        elsif v_new->>'ends_at' is distinct from v_old->>'ends_at' or (v_new->'config') is distinct from (v_old->'config') then
          v_action := 'campaign.update'; v_det := jsonb_build_object('ends_at', v_new->>'ends_at');
        else return null; end if;
      end if;
    when 'mega_campaign_shops' then
      v_camp := (v_row->>'campaign_id')::uuid; v_ent := (v_row->>'business_id')::uuid;
      v_action := case tg_op when 'INSERT' then 'shop.add' else 'shop.remove' end;
    when 'mega_enrollments' then
      v_camp := (v_row->>'campaign_id')::uuid; v_ent := (v_row->>'id')::uuid; v_action := 'enrollment.create';
      v_det := jsonb_build_object('customer_id', v_row->>'customer_id');
    when 'mega_partner_participation' then
      v_camp := (v_row->>'campaign_id')::uuid; v_ent := (v_row->>'business_id')::uuid;
      if tg_op = 'INSERT' then v_action := 'partner.invited';
      elsif v_new->>'status' is distinct from v_old->>'status' then
        v_action := 'partner.' || (v_new->>'status'); v_det := jsonb_build_object('from', v_old->>'status', 'to', v_new->>'status');
      else return null; end if;
    when 'mega_service_verifications' then
      v_store := (v_row->>'mega_store_id')::uuid; v_camp := (v_row->>'campaign_id')::uuid; v_ent := (v_row->>'id')::uuid;
      if tg_op = 'INSERT' then v_action := 'service.verified'; v_det := jsonb_build_object('booking_id', v_row->>'booking_id', 'business_id', v_row->>'business_id');
      elsif v_new->>'status' is distinct from v_old->>'status' then
        v_action := 'service.' || (v_new->>'status'); v_det := jsonb_build_object('from', v_old->>'status', 'to', v_new->>'status');
      else return null; end if;
    when 'mega_fraud_flags' then
      v_store := (v_row->>'mega_store_id')::uuid; v_camp := (v_row->>'campaign_id')::uuid; v_ent := (v_row->>'id')::uuid;
      if tg_op = 'INSERT' then v_action := 'flag.raise'; v_det := jsonb_build_object('type', v_row->>'flag_type', 'source', v_row->>'source');
      elsif v_new->>'status' is distinct from v_old->>'status' then
        v_action := 'flag.' || (v_new->>'status'); v_det := jsonb_build_object('type', v_row->>'flag_type', 'from', v_old->>'status');
      else return null; end if;
    when 'mega_store_members' then
      v_store := (v_row->>'mega_store_id')::uuid; v_ent := (v_row->>'user_id')::uuid;
      if tg_op = 'INSERT' then v_action := 'member.add'; v_det := jsonb_build_object('role', v_row->>'member_role');
      elsif v_new->>'status' is distinct from v_old->>'status' then v_action := 'member.' || (v_new->>'status');
      else return null; end if;
    when 'mega_terms' then
      v_camp := (v_row->>'campaign_id')::uuid; v_ent := (v_row->>'id')::uuid; v_action := 'terms.publish';
      v_det := jsonb_build_object('scope', v_row->>'scope', 'version', v_row->>'version');
    when 'mega_terms_acceptances' then
      v_camp := (v_row->>'campaign_id')::uuid; v_ent := (v_row->>'id')::uuid; v_action := 'terms.accept';
      v_det := jsonb_build_object('scope', v_row->>'scope', 'terms_id', v_row->>'terms_id', 'business_id', v_row->>'business_id');
    when 'mega_reward_redemptions' then
      v_store := (v_row->>'mega_store_id')::uuid; v_camp := (v_row->>'campaign_id')::uuid; v_ent := (v_row->>'id')::uuid;
      v_action := 'redemption.record'; v_det := jsonb_build_object('reward_id', v_row->>'reward_id', 'bill_inr', v_row->>'bill_inr', 'discount_inr', v_row->>'discount_inr');
    else
      return null;
  end case;
  if v_store is null and v_camp is not null then
    select c.mega_store_id into v_store from public.mega_campaigns c where c.id = v_camp;
  end if;
  perform public.mega_audit(v_action, v_store, v_camp, regexp_replace(tg_table_name, '^mega_', ''), v_ent, v_det);
  return null;
end $$;

-- ============ 7. TRIGGERS ============
drop trigger if exists mega_stores_owner_member on public.mega_stores;
create trigger mega_stores_owner_member after insert on public.mega_stores
  for each row execute function public.mega_store_add_owner_member();

drop trigger if exists mega_members_guard on public.mega_store_members;
create trigger mega_members_guard before update on public.mega_store_members
  for each row execute function public.mega_members_guard();

drop trigger if exists mega_campaign_guard on public.mega_campaigns;
create trigger mega_campaign_guard before update on public.mega_campaigns
  for each row execute function public.mega_campaign_guard();

drop trigger if exists mega_shop_link_guard on public.mega_campaign_shops;
create trigger mega_shop_link_guard before insert on public.mega_campaign_shops
  for each row execute function public.mega_shop_link_guard();
drop trigger if exists mega_shop_unlink on public.mega_campaign_shops;
create trigger mega_shop_unlink after delete on public.mega_campaign_shops
  for each row execute function public.mega_shop_unlink();

drop trigger if exists mega_enrollment_guard on public.mega_enrollments;
create trigger mega_enrollment_guard before insert on public.mega_enrollments
  for each row execute function public.mega_enrollment_guard();

create trigger mega_rewards_guard before insert or update on public.mega_rewards
  for each row execute function public.mega_reward_guard();
create trigger mega_rewards_after after insert or update on public.mega_rewards
  for each row execute function public.mega_reward_after();

create trigger mega_redemptions_guard before insert on public.mega_reward_redemptions
  for each row execute function public.mega_redemption_guard();

-- immutable evidence: terms, acceptances, redemptions never change; the audit log can never be changed, deleted or truncated
drop trigger if exists mega_terms_immutable on public.mega_terms;
create trigger mega_terms_immutable before update on public.mega_terms for each row execute function public.mega_block_update();
drop trigger if exists mega_terms_acc_immutable on public.mega_terms_acceptances;
create trigger mega_terms_acc_immutable before update on public.mega_terms_acceptances for each row execute function public.mega_block_update();
drop trigger if exists mega_redemptions_immutable on public.mega_reward_redemptions;
create trigger mega_redemptions_immutable before update on public.mega_reward_redemptions for each row execute function public.mega_block_update();
drop trigger if exists mega_audit_immutable on public.mega_audit_log;
create trigger mega_audit_immutable before update or delete on public.mega_audit_log for each row execute function public.mega_block_update();
drop trigger if exists mega_audit_no_truncate on public.mega_audit_log;
create trigger mega_audit_no_truncate before truncate on public.mega_audit_log for each statement execute function public.mega_block_update();

-- audit triggers
drop trigger if exists mega_audit_stores on public.mega_stores;
create trigger mega_audit_stores after insert or update on public.mega_stores for each row execute function public.mega_audit_trigger();
drop trigger if exists mega_audit_campaigns on public.mega_campaigns;
create trigger mega_audit_campaigns after insert or update on public.mega_campaigns for each row execute function public.mega_audit_trigger();
drop trigger if exists mega_audit_shops on public.mega_campaign_shops;
create trigger mega_audit_shops after insert or delete on public.mega_campaign_shops for each row execute function public.mega_audit_trigger();
drop trigger if exists mega_audit_enrollments on public.mega_enrollments;
create trigger mega_audit_enrollments after insert on public.mega_enrollments for each row execute function public.mega_audit_trigger();
drop trigger if exists mega_audit_participation on public.mega_partner_participation;
create trigger mega_audit_participation after insert or update on public.mega_partner_participation for each row execute function public.mega_audit_trigger();
drop trigger if exists mega_audit_verifications on public.mega_service_verifications;
create trigger mega_audit_verifications after insert or update on public.mega_service_verifications for each row execute function public.mega_audit_trigger();
drop trigger if exists mega_audit_flags on public.mega_fraud_flags;
create trigger mega_audit_flags after insert or update on public.mega_fraud_flags for each row execute function public.mega_audit_trigger();
drop trigger if exists mega_audit_members on public.mega_store_members;
create trigger mega_audit_members after insert or update on public.mega_store_members for each row execute function public.mega_audit_trigger();
drop trigger if exists mega_audit_terms on public.mega_terms;
create trigger mega_audit_terms after insert on public.mega_terms for each row execute function public.mega_audit_trigger();
drop trigger if exists mega_audit_terms_acc on public.mega_terms_acceptances;
create trigger mega_audit_terms_acc after insert on public.mega_terms_acceptances for each row execute function public.mega_audit_trigger();
drop trigger if exists mega_audit_redemptions on public.mega_reward_redemptions;
create trigger mega_audit_redemptions after insert on public.mega_reward_redemptions for each row execute function public.mega_audit_trigger();

-- ============ 8. FUNCTIONS (all writes go through here; the browser never sends ids, roles, amounts or statuses) ============
-- authorised members -----------------------------------------------------------------------------------------------
create or replace function public.megastore_add_member(p_email text) returns void
language plpgsql security definer set search_path = '' as $$
declare m public.mega_stores; v_uid uuid;
begin
  if not public.is_owner() then raise exception 'owner_only' using errcode = '42501'; end if;
  select * into m from public.mega_stores where owner_id = auth.uid();                    -- only the PRIMARY owner manages members
  if not found then raise exception 'not_found' using errcode = 'P0002'; end if;
  if m.status <> 'approved' then raise exception 'store_not_approved'; end if;
  select u.id into v_uid from auth.users u where lower(u.email::text) = lower(trim(coalesce(p_email, '')));
  if v_uid is null or v_uid = auth.uid()
     or not exists (select 1 from public.profiles p where p.id = v_uid and p.role = 'owner' and not p.is_suspended) then
    raise exception 'user_not_eligible';                                                  -- same answer for every failure (no e-mail probing)
  end if;
  insert into public.mega_store_members (mega_store_id, user_id, member_role, added_by)
  values (m.id, v_uid, 'manager', auth.uid())
  on conflict (mega_store_id, user_id) do update set status = 'active', revoked_at = null, added_by = auth.uid()
   where public.mega_store_members.status = 'revoked';
end $$;

create or replace function public.megastore_revoke_member(p_user_id uuid) returns void
language plpgsql security definer set search_path = '' as $$
declare m public.mega_stores;
begin
  if not public.is_owner() then raise exception 'owner_only' using errcode = '42501'; end if;
  select * into m from public.mega_stores where owner_id = auth.uid();
  if not found then raise exception 'not_found' using errcode = 'P0002'; end if;
  update public.mega_store_members set status = 'revoked', revoked_at = now()
   where mega_store_id = m.id and user_id = p_user_id and status = 'active';             -- the primary owner is protected by the trigger
  if not found then raise exception 'not_found' using errcode = 'P0002'; end if;
end $$;

-- budget -----------------------------------------------------------------------------------------------------------
create or replace function public.megastore_set_campaign_budget(p_campaign_id uuid, p_budget numeric) returns void
language plpgsql security definer set search_path = '' as $$
declare c public.mega_campaigns; v_status text;
begin
  if auth.uid() is null then raise exception 'not authenticated' using errcode = '28000'; end if;
  select * into c from public.mega_campaigns where id = p_campaign_id for update;
  if not found or not (public.owns_mega_store(c.mega_store_id) or public.is_admin()) then raise exception 'not_found' using errcode = 'P0002'; end if;
  select status into v_status from public.mega_stores where id = c.mega_store_id;
  if v_status <> 'approved' and not public.is_admin() then raise exception 'store_not_approved'; end if;
  if c.status = 'ended' then raise exception 'campaign_locked'; end if;
  if p_budget is not null and (p_budget <= 0 or p_budget > 1000000000) then raise exception 'invalid_budget'; end if;
  update public.mega_campaigns set budget_inr = p_budget where id = c.id;                  -- trigger refuses a budget below what was spent
end $$;

create or replace function public.get_mega_campaign_budget(p_campaign_id uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare c public.mega_campaigns; v_spent numeric; v_n int;
begin
  if auth.uid() is null then raise exception 'not authenticated' using errcode = '28000'; end if;
  select * into c from public.mega_campaigns where id = p_campaign_id;
  if not found or not (public.owns_mega_store(c.mega_store_id) or public.is_admin()) then raise exception 'not_found' using errcode = 'P0002'; end if;
  select coalesce(sum(discount_inr), 0), count(*)::int into v_spent, v_n from public.mega_reward_redemptions where campaign_id = c.id;
  return jsonb_build_object('campaign_id', c.id, 'budget_inr', c.budget_inr, 'spent_inr', v_spent, 'redemptions', v_n,
    'remaining_inr', case when c.budget_inr is null then null else greatest(c.budget_inr - v_spent, 0) end);
end $$;

-- terms ------------------------------------------------------------------------------------------------------------
create or replace function public._mega_insert_terms(p_campaign_id uuid, p_scope text, p_title text, p_body text) returns uuid
language plpgsql security definer set search_path = '' as $$
declare v_ver int; v_id uuid;
begin
  if p_scope not in ('customer', 'partner') then raise exception 'invalid_scope'; end if;
  perform pg_advisory_xact_lock(hashtext('mega_terms:' || coalesce(p_campaign_id::text, 'default') || ':' || p_scope));
  select coalesce(max(version), 0) + 1 into v_ver from public.mega_terms
   where scope = p_scope and coalesce(campaign_id, '00000000-0000-0000-0000-000000000000'::uuid) = coalesce(p_campaign_id, '00000000-0000-0000-0000-000000000000'::uuid);
  insert into public.mega_terms (campaign_id, scope, version, title, body_md, created_by)
  values (p_campaign_id, p_scope, v_ver, trim(p_title), p_body, auth.uid()) returning id into v_id;
  return v_id;
end $$;

create or replace function public.admin_publish_mega_terms(p_scope text, p_title text, p_body text, p_campaign_id uuid default null) returns uuid
language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_admin() then raise exception 'admin only' using errcode = '42501'; end if;
  if p_campaign_id is not null and not exists (select 1 from public.mega_campaigns where id = p_campaign_id) then raise exception 'not_found' using errcode = 'P0002'; end if;
  return public._mega_insert_terms(p_campaign_id, p_scope, p_title, p_body);
end $$;

-- the Mega Store owner can attach terms to their own campaign while it is still a draft
create or replace function public.megastore_publish_campaign_terms(p_scope text, p_title text, p_body text) returns uuid
language plpgsql security definer set search_path = '' as $$
declare m public.mega_stores; c public.mega_campaigns;
begin
  if not public.is_owner() then raise exception 'owner_only' using errcode = '42501'; end if;
  select * into m from public.mega_stores where owner_id = auth.uid();
  if not found then raise exception 'not_found' using errcode = 'P0002'; end if;
  if m.status <> 'approved' then raise exception 'store_not_approved'; end if;
  select * into c from public.mega_campaigns where mega_store_id = m.id and status in ('draft', 'active', 'paused') for update;
  if not found then raise exception 'no_campaign'; end if;
  if c.status <> 'draft' then raise exception 'campaign_locked'; end if;
  return public._mega_insert_terms(c.id, p_scope, p_title, p_body);
end $$;

create or replace function public.get_mega_terms(p_campaign_id uuid, p_scope text) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare t public.mega_terms; v_id uuid; v_acc boolean := false;
begin
  if p_scope not in ('customer', 'partner') then raise exception 'invalid_scope'; end if;
  if not public.mega_terms_visible(p_campaign_id) then raise exception 'not_found' using errcode = 'P0002'; end if;
  v_id := public.mega_current_terms(p_campaign_id, p_scope);
  if v_id is null then return jsonb_build_object('terms', null, 'accepted', false); end if;
  select * into t from public.mega_terms where id = v_id;
  if auth.uid() is not null and p_campaign_id is not null then
    select exists (select 1 from public.mega_terms_acceptances a where a.terms_id = v_id and a.user_id = auth.uid() and a.campaign_id = p_campaign_id) into v_acc;
  end if;
  return jsonb_build_object('terms', jsonb_build_object('id', t.id, 'version', t.version, 'title', t.title, 'body_md', t.body_md), 'accepted', v_acc);
end $$;

-- records that the SIGNED-IN user accepted the CURRENT terms (the user id and the version come from the server, not the browser)
create or replace function public.accept_mega_terms(p_campaign_id uuid, p_scope text, p_business_id uuid default null) returns void
language plpgsql security definer set search_path = '' as $$
declare c public.mega_campaigns; pr public.profiles; v_terms uuid;
begin
  if auth.uid() is null then raise exception 'not authenticated' using errcode = '28000'; end if;
  select * into pr from public.profiles where id = auth.uid();
  if not found or pr.is_suspended then raise exception 'not_available' using errcode = '42501'; end if;
  select * into c from public.mega_campaigns where id = p_campaign_id;
  if not found then raise exception 'not_found' using errcode = 'P0002'; end if;
  if p_scope = 'customer' then
    if pr.role <> 'customer' then raise exception 'customer_only'; end if;
    if c.status <> 'active' or c.ends_at <= now() then raise exception 'not_active'; end if;
  elsif p_scope = 'partner' then
    if p_business_id is null or not public.owns_business(p_business_id) then raise exception 'not_authorized' using errcode = '42501'; end if;
    if not exists (select 1 from public.mega_campaign_shops s where s.campaign_id = c.id and s.business_id = p_business_id) then raise exception 'not_partner_shop'; end if;
  else
    raise exception 'invalid_scope';
  end if;
  v_terms := public.mega_current_terms(c.id, p_scope);
  if v_terms is null then raise exception 'no_terms'; end if;
  insert into public.mega_terms_acceptances (terms_id, user_id, campaign_id, scope, business_id)
  values (v_terms, auth.uid(), c.id, p_scope, case when p_scope = 'partner' then p_business_id end)
  on conflict do nothing;
end $$;

-- partner shops ----------------------------------------------------------------------------------------------------
create or replace function public.partner_respond_mega_campaign(p_campaign_id uuid, p_business_id uuid, p_accept boolean) returns void
language plpgsql security definer set search_path = '' as $$
declare p public.mega_partner_participation; c public.mega_campaigns; v_terms uuid;
begin
  if auth.uid() is null then raise exception 'not authenticated' using errcode = '28000'; end if;
  if not public.owns_business(p_business_id) then raise exception 'not_authorized' using errcode = '42501'; end if;
  select * into c from public.mega_campaigns where id = p_campaign_id;
  if not found or c.status = 'ended' then raise exception 'not_active'; end if;
  select * into p from public.mega_partner_participation where campaign_id = p_campaign_id and business_id = p_business_id for update;
  if not found then raise exception 'not_found' using errcode = 'P0002'; end if;
  if p_accept is true then
    if p.status <> 'invited' then raise exception 'invalid_transition'; end if;
    v_terms := public.mega_current_terms(c.id, 'partner');
    if v_terms is not null and not exists (select 1 from public.mega_terms_acceptances a
         where a.terms_id = v_terms and a.user_id = auth.uid() and a.campaign_id = c.id and a.business_id = p_business_id) then
      raise exception 'terms_not_accepted';
    end if;
    update public.mega_partner_participation set status = 'accepted', responded_at = now(), responded_by = auth.uid(), terms_id = v_terms
     where campaign_id = p.campaign_id and business_id = p.business_id;
  else
    if p.status not in ('invited', 'accepted') then raise exception 'invalid_transition'; end if;
    update public.mega_partner_participation
       set status = case when p.status = 'accepted' then 'withdrawn' else 'declined' end, responded_at = now(), responded_by = auth.uid()
     where campaign_id = p.campaign_id and business_id = p.business_id;
    delete from public.mega_campaign_shops where campaign_id = p.campaign_id and business_id = p.business_id;   -- stops new rewards at this shop
  end if;
end $$;

-- a partner shop sees ONLY the verification facts it needs (no reward code, amount or customer contact)
create or replace function public.partner_list_mega_services(p_business_id uuid) returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v_out jsonb;
begin
  if auth.uid() is null then raise exception 'not authenticated' using errcode = '28000'; end if;
  if not public.owns_business(p_business_id) then raise exception 'not_authorized' using errcode = '42501'; end if;
  select coalesce(jsonb_agg(x.j order by x.at desc), '[]'::jsonb) into v_out
    from (select v.verified_at as at,
                 jsonb_build_object('booking_id', v.booking_id, 'status', v.status, 'service', v.service_label, 'price_inr', v.service_price_inr,
                   'completed_at', v.service_completed_at, 'verified_at', v.verified_at, 'campaign_title', c.title, 'store_name', ms.name,
                   'customer_first_name', coalesce(split_part(p.full_name, ' ', 1), '')) as j
            from public.mega_service_verifications v
            join public.mega_campaigns c on c.id = v.campaign_id
            join public.mega_stores ms on ms.id = v.mega_store_id
            join public.profiles p on p.id = v.customer_id
           where v.business_id = p_business_id
           order by v.verified_at desc limit 100) x;
  return v_out;
end $$;

-- admin ------------------------------------------------------------------------------------------------------------
create or replace function public.admin_mega_set_service_status(p_booking_id uuid, p_status text, p_note text default null) returns void
language plpgsql security definer set search_path = '' as $$
declare v public.mega_service_verifications;
begin
  if not public.is_admin() then raise exception 'admin only' using errcode = '42501'; end if;
  if p_status not in ('verified', 'revoked', 'rejected') then raise exception 'invalid_status'; end if;
  select * into v from public.mega_service_verifications where booking_id = p_booking_id for update;
  if not found then raise exception 'not_found' using errcode = 'P0002'; end if;
  update public.mega_service_verifications
     set status = p_status, method = 'admin', verified_by = auth.uid(), note = left(nullif(trim(coalesce(p_note, '')), ''), 300)
   where id = v.id;
  if p_status <> 'verified' then                                     -- an unverified service cannot back a reward (redeemed ones stay as history)
    update public.mega_rewards set status = 'revoked', review_note = left(nullif(trim(coalesce(p_note, '')), ''), 300),
           reviewed_by = auth.uid(), reviewed_at = now()
     where booking_id = p_booking_id and status in ('active', 'on_hold');
  end if;
end $$;

create or replace function public.admin_mega_review_flag(p_flag_id uuid, p_decision text, p_note text default null) returns void
language plpgsql security definer set search_path = '' as $$
declare f public.mega_fraud_flags;
begin
  if not public.is_admin() then raise exception 'admin only' using errcode = '42501'; end if;
  if p_decision not in ('cleared', 'confirmed') then raise exception 'invalid_decision'; end if;
  select * into f from public.mega_fraud_flags where id = p_flag_id for update;
  if not found then raise exception 'not_found' using errcode = 'P0002'; end if;
  if f.status <> 'open' then raise exception 'invalid_transition'; end if;
  update public.mega_fraud_flags set status = p_decision, reviewed_by = auth.uid(), reviewed_at = now(),
         review_note = left(nullif(trim(coalesce(p_note, '')), ''), 300) where id = f.id;
  if p_decision = 'confirmed' and f.reward_id is not null then      -- confirmed fraud cancels the reward if it is not redeemed yet
    update public.mega_rewards set status = 'revoked', review_note = left(nullif(trim(coalesce(p_note, '')), ''), 300),
           reviewed_by = auth.uid(), reviewed_at = now()
     where id = f.reward_id and status in ('active', 'on_hold');
  end if;
end $$;

create or replace function public.admin_mega_raise_flag(p_reward_id uuid, p_flag_type text, p_note text default null) returns uuid
language plpgsql security definer set search_path = '' as $$
declare r public.mega_rewards; v_id uuid; v_type text := lower(trim(coalesce(p_flag_type, '')));
begin
  if not public.is_admin() then raise exception 'admin only' using errcode = '42501'; end if;
  if v_type !~ '^[a-z0-9_]{3,40}$' then raise exception 'invalid_flag_type'; end if;
  select * into r from public.mega_rewards where id = p_reward_id;
  if not found then raise exception 'not_found' using errcode = 'P0002'; end if;
  insert into public.mega_fraud_flags (campaign_id, mega_store_id, reward_id, customer_id, business_id, flag_type, severity, source, details)
  values (r.campaign_id, r.mega_store_id, r.id, r.customer_id, r.business_id, v_type, 'high', 'admin',
          jsonb_build_object('note', left(nullif(trim(coalesce(p_note, '')), ''), 300)))
  on conflict do nothing returning id into v_id;
  if v_id is null then raise exception 'already_flagged'; end if;
  return v_id;
end $$;

-- ============ 9. RLS (read only; every write goes through the functions / triggers above) ============
alter table public.mega_store_members enable row level security;
alter table public.mega_service_verifications enable row level security;
alter table public.mega_terms enable row level security;
alter table public.mega_terms_acceptances enable row level security;
alter table public.mega_partner_participation enable row level security;
alter table public.mega_reward_redemptions enable row level security;
alter table public.mega_fraud_flags enable row level security;
alter table public.mega_audit_log enable row level security;

-- EXTENDED (not weakened): the Mega Store row is also visible to the store's authorised members. Before: primary owner or admin.
drop policy if exists mega_stores_select on public.mega_stores;
create policy mega_stores_select on public.mega_stores for select to authenticated
  using (public.owns_mega_store(id) or public.is_admin());

drop policy if exists mega_members_select on public.mega_store_members;
create policy mega_members_select on public.mega_store_members for select to authenticated
  using (user_id = auth.uid() or public.owns_mega_store(mega_store_id) or public.is_admin());

-- partner shops get NO direct access here; they use partner_list_mega_services() which returns only what they need
drop policy if exists mega_sv_select on public.mega_service_verifications;
create policy mega_sv_select on public.mega_service_verifications for select to authenticated
  using (customer_id = auth.uid() or public.owns_mega_store(mega_store_id) or public.is_admin());

drop policy if exists mega_terms_select on public.mega_terms;
create policy mega_terms_select on public.mega_terms for select to anon, authenticated
  using (public.mega_terms_visible(campaign_id));

drop policy if exists mega_terms_acc_select on public.mega_terms_acceptances;
create policy mega_terms_acc_select on public.mega_terms_acceptances for select to authenticated
  using (user_id = auth.uid() or public.owns_mega_campaign(campaign_id) or public.is_admin());

drop policy if exists mega_pp_select on public.mega_partner_participation;
create policy mega_pp_select on public.mega_partner_participation for select to authenticated
  using (public.owns_business(business_id) or public.owns_mega_campaign(campaign_id) or public.is_admin());

drop policy if exists mega_redemptions_select on public.mega_reward_redemptions;
create policy mega_redemptions_select on public.mega_reward_redemptions for select to authenticated
  using (customer_id = auth.uid() or public.owns_mega_store(mega_store_id) or public.is_admin());

-- fraud flags and the audit trail are never visible to customers or partner shops
drop policy if exists mega_flags_select on public.mega_fraud_flags;
create policy mega_flags_select on public.mega_fraud_flags for select to authenticated
  using (public.owns_mega_store(mega_store_id) or public.is_admin());

drop policy if exists mega_audit_select on public.mega_audit_log;
create policy mega_audit_select on public.mega_audit_log for select to authenticated
  using (public.is_admin() or (mega_store_id is not null and public.owns_mega_store(mega_store_id)));

revoke all on public.mega_store_members, public.mega_service_verifications, public.mega_terms, public.mega_terms_acceptances,
  public.mega_partner_participation, public.mega_reward_redemptions, public.mega_fraud_flags, public.mega_audit_log
  from anon, authenticated;
grant select on public.mega_store_members, public.mega_service_verifications, public.mega_terms_acceptances,
  public.mega_partner_participation, public.mega_reward_redemptions, public.mega_fraud_flags, public.mega_audit_log to authenticated;
grant select on public.mega_terms to anon, authenticated;       -- terms are public reading (the QR page shows them before login)

-- ============ 10. FUNCTION PRIVILEGES ============
revoke execute on function
  public.owns_mega_campaign(uuid), public.mega_terms_visible(uuid), public.mega_current_terms(uuid, text), public.mega_new_reward_code(),
  public.mega_audit(text, uuid, uuid, text, uuid, jsonb), public.mega_block_update(), public.mega_members_guard(),
  public.mega_store_add_owner_member(), public.mega_campaign_guard(), public.mega_shop_link_guard(), public.mega_shop_unlink(),
  public.mega_enrollment_guard(), public.mega_reward_guard(), public.mega_reward_after(), public.mega_redemption_guard(),
  public.mega_audit_trigger(), public._mega_insert_terms(uuid, text, text, text),
  public.megastore_add_member(text), public.megastore_revoke_member(uuid), public.megastore_set_campaign_budget(uuid, numeric),
  public.get_mega_campaign_budget(uuid), public.admin_publish_mega_terms(text, text, text, uuid),
  public.megastore_publish_campaign_terms(text, text, text), public.get_mega_terms(uuid, text),
  public.accept_mega_terms(uuid, text, uuid), public.partner_respond_mega_campaign(uuid, uuid, boolean),
  public.partner_list_mega_services(uuid), public.admin_mega_set_service_status(uuid, text, text),
  public.admin_mega_review_flag(uuid, text, text), public.admin_mega_raise_flag(uuid, text, text)
  from public, anon, authenticated;
revoke execute on function public.owns_mega_store(uuid) from public, anon;

-- needed because RLS policies call them with the caller's rights
grant execute on function public.owns_mega_store(uuid), public.owns_mega_campaign(uuid) to authenticated;
grant execute on function public.mega_terms_visible(uuid) to anon, authenticated;
grant execute on function
  public.megastore_add_member(text), public.megastore_revoke_member(uuid), public.megastore_set_campaign_budget(uuid, numeric),
  public.get_mega_campaign_budget(uuid), public.admin_publish_mega_terms(text, text, text, uuid),
  public.megastore_publish_campaign_terms(text, text, text), public.accept_mega_terms(uuid, text, uuid),
  public.partner_respond_mega_campaign(uuid, uuid, boolean), public.partner_list_mega_services(uuid),
  public.admin_mega_set_service_status(uuid, text, text), public.admin_mega_review_flag(uuid, text, text),
  public.admin_mega_raise_flag(uuid, text, text)
  to authenticated;
grant execute on function public.get_mega_terms(uuid, text) to anon, authenticated;
